### ISSUE TITLE
Uglifier

### ISSUE THREAD

**Issue by OxideOG** [Herrtt/luamin.js#22]
Hello! I've recently found this repository and i think it's great. The use i was searching in this is the uglifier, which in my eyes seems to have been removed. I tried using an older version, but the uglifier didn't work for my project since it threw errors. I'm trying to use it for uglifying the lua code in fivem scripts.

Is there a reason why uglifier was removed, if so is there any other uglifier that would work for FiveM?

**Comment by quanmanss11** [comment]
> Hello! I've recently found this repository and i think it's great. The use i was searching in this is the uglifier, which in my eyes seems to have been removed. I tried using an older version, but the uglifier didn't work for my project since it threw errors. I'm trying to use it for uglifying the lua code in fivem scripts.
> 
> Is there a reason why uglifier was removed, if so is there any other uglifier that would work for FiveM?

https://vanilla-ac.com/obfuscator/
