### ISSUE TITLE
[BUG] Minifier not minifying into a one-liner

### ISSUE THREAD

**Issue by phoriah** [Herrtt/luamin.js#23]
My 6k line script completely breaks the minifier provided here.
An example would be Infinite Yield's source code - it breaks it too. By breaks I mean that I expect it to be a one-liner instead of this (below).
![unknown](https://user-images.githubusercontent.com/95628489/194991249-adad975f-9ef5-420e-be94-ef39e72c990a.png)
Thanks, 
P.

**Comment by XbcqEqualCool** [comment]
try using an older version of luamin, ive had the same issue lmao

**Comment by Herrtt** [comment]
Fixed this issue and updated the npm package + github code.
