### ISSUE TITLE
doesnt work - or i did something wrong

### ISSUE THREAD

**Issue by dothuraki** [Herrtt/luamin.js#28]
(1) beautify (2) minify
choose option: 2
Tokens[-3] = ``
Tokens[-2] = ``
Tokens[-1] = `paste`
Tokens[0] = `code`
Tokens[1] = `here`
Tokens[2] = ``
Tokens[3] = ``

C:\Users\playa\OneDrive\Masaüstü\luamin.js-master\src\luamin.js:640
                throw a
                ^
1:9: `=` expected.
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v18.17.1
minified

**Comment by Herrtt** [comment]
Looks like you forgot to change the input.lua code.
