### ISSUE TITLE
Add Support for the Floor Division Operator (//)

### ISSUE THREAD

**Issue by phoriah** [Herrtt/luamin.js#32]
At least for the Minify mode.
```lua
local x = 10 // 5
print(x) --> 2
```
`1:21: Unexpected symbol. Symbol /`
![image](https://github.com/Herrtt/luamin.js/assets/95628489/e4d3dfa8-0cf1-4280-8c2e-febf51a803be)

Compound:
```lua
local x = 10
x //= 2
print(x) --> 5
```
``2:5: `=` expected.``
![image](https://github.com/Herrtt/luamin.js/assets/95628489/53bebfdd-60ef-48b2-adb0-a5771c5c85a1)

Sources:
https://luau-lang.org/syntax#floor-division-
https://devforum.roblox.com/t/luau-recap-october-2023/2685332#floor-division-1

**Comment by Herrtt** [comment]
Added this in the latest publish (1.5.0).
